import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdir, readFile } from 'node:fs/promises';

const base=process.env.BASE_URL || 'http://localhost:5173/ManuscriptMaker/';
await mkdir('.local',{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME||undefined});
const context=await browser.newContext({viewport:{width:1360,height:900},acceptDownloads:true});
const page=await context.newPage();
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
const download=async(name)=>{const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Save project',exact:true}).click();const file=await pending;await file.saveAs(`.local/${name}`);return JSON.parse(await readFile(`.local/${name}`,'utf8'))};
try{
  await page.goto(base);
  await page.getByRole('button',{name:'Make a manuscript'}).click();
  await page.getByRole('button',{name:/Playable crossing/}).click();
  await page.getByRole('button',{name:'Create book',exact:true}).click();
  await expect(page.getByLabel('Current book page')).toContainText('Page 1 of 1');
  const playerRow=page.locator('.layer-row').filter({hasText:'The traveller'});
  await playerRow.getByRole('button',{name:'The traveller',exact:true}).click();
  await expect(page.getByLabel('Play role')).toHaveValue('player');
  const original=await download('play-before.json');
  const player=original.pages[0].layers.find(layer=>layer.gameRole==='player');
  assert.ok(player);
  assert.ok(original.pages[0].layers.some(layer=>layer.gameRole==='platform'));
  await page.getByRole('button',{name:'Play scene',exact:true}).click();
  await expect(page.getByLabel(/playable scene/)).toBeVisible();
  // The character is drawn on the play canvas; read its feet from the running session.
  const feetX=()=>page.evaluate(()=>{const s=window.__playSession;return s?(s.world.body.x+s.world.body.w/2)*s.spec.field.cell:null});
  await page.waitForFunction(()=>!!window.__playSession);
  await page.waitForTimeout(300);
  const start=await feetX();
  assert.ok(Math.abs(start-(player.x+player.width/2))<player.width/2,`Character should start at its layer, got ${start}`);
  await page.keyboard.down('ArrowRight');
  await page.waitForTimeout(350);
  await page.keyboard.up('ArrowRight');
  const moved=await feetX();
  assert.ok(moved>start+15,`Expected movement, got ${moved} from ${start}`);
  await page.getByRole('button',{name:'Restart playtest'}).click();
  await page.waitForTimeout(100);
  assert.ok(Math.abs(await feetX()-start)<2,'Restart returns the character to the start');
  const after=await download('play-after.json');
  assert.deepEqual(after.pages,original.pages,'Play must not change saved manuscript content');
  await page.getByRole('button',{name:'Return to editor'}).click();
  await expect(page.locator('#manuscript-page')).toBeVisible();
  await page.screenshot({path:'.local/play-workshop.png',fullPage:true});
  await page.getByRole('button',{name:'Play scene',exact:true}).click();
  await page.screenshot({path:'.local/play-preview.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Restart playtest'}).click();
  const right=page.getByRole('button',{name:'Move right'});
  await expect(right).toBeVisible();
  const bounds=await right.boundingBox();
  assert.ok(bounds);
  await page.mouse.move(bounds.x+bounds.width/2,bounds.y+bounds.height/2);
  await page.mouse.down();await page.waitForTimeout(300);await page.mouse.up();
  assert.ok(await feetX()>start+10,'Touch controls move the character');
  assert.ok(await page.evaluate(()=>document.body.scrollWidth)<=390);
  await page.screenshot({path:'.local/play-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('PASS crossing template, role inspector, keyboard/touch controls, restart, read-only play save, edit return, mobile fit, no runtime errors');
}finally{await browser.close()}
